name: My First Workflow

on: [push]    # トリガー: プッシュされたら動く

jobs:
  hello-job:
    runs-on: ubuntu-latest  # 環境: 最新のUbuntu（Linux）を使う
    steps:
      - name: Say Hello
        run: echo "Hello, GitHub Actions!"  # 実行: コマンドを実行